version: '3.7'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  app:
    build: .
    command: >
      sh -c "python3 ./app/manage.py migrate &&
             python3 ./app/manage.py runserver 0.0.0.0:8000 &&
             python3 ./app/manage.py bot 0.0.0.0:8001"
    env_file:
      - ./app/.env
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: