# Generated by Django 5.0 on 2023-12-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('BASIC', 'Basic State'), ('WAIT_FOR_EMAIL', 'Wait for Email'), ('WAIT_FOR_MEDIA', 'Wait for Media')], default='BASIC'),
        ),
        migrations.CreateModel(
            name='CurrentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(verbose_name='Message ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.profile')),
            ],
            options={
                'verbose_name': 'CurrentAction',
                'verbose_name_plural': 'CurrentActions',
            },
        ),
    ]
