# Generated by Django 5.0 on 2023-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_alter_profile_state_currentaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('WAIT_FOR_MEDIA', 'Wait for Media'), ('WAIT_FOR_EMAIL', 'Wait for Email'), ('BASIC', 'Basic State')], default='BASIC'),
        ),
    ]
