# Generated by Django 5.0 on 2023-12-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('WAIT_FOR_EMAIL', 'Wait for Email'), ('WAIT_FOR_MEDIA', 'Wait for Media'), ('BASIC', 'Basic State')], default='BASIC'),
        ),
        migrations.DeleteModel(
            name='MediaProfileHashtag',
        ),
    ]
