# Generated by Django 5.0 on 2024-01-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_alter_profile_state_delete_mediaprofilehashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
