# Generated by Django 5.0 on 2024-01-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=255, unique=True, verbose_name='Media ID')),
                ('telegram_video_file_id', models.CharField(max_length=255, verbose_name='Telegram Video File ID')),
                ('telegram_audio_file_id', models.CharField(max_length=255, verbose_name='Telegram Audio File ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('url', models.TextField(verbose_name='Url')),
                ('channel', models.TextField(verbose_name='Channel')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('date_of_addition', models.DateTimeField(auto_now_add=True, verbose_name='Date of addition')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(unique=True, verbose_name='Profile ID')),
                ('username', models.TextField(null=True, verbose_name='Username')),
                ('first_name', models.TextField(null=True, verbose_name='First Name')),
                ('last_name', models.TextField(null=True, verbose_name='Last Name')),
                ('first_login_date', models.DateTimeField(auto_now_add=True, verbose_name='First login date')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Role name')),
                ('delay_between_downloads', models.PositiveIntegerField(verbose_name='Delay between downloads')),
                ('allowed_media_length', models.PositiveIntegerField(verbose_name='Allowed Media Length')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='MediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(verbose_name='Message ID')),
                ('download_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Downloaded')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_cloud.media')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_cloud.profile')),
            ],
            options={
                'verbose_name': 'Media Download',
                'verbose_name_plural': 'Media Downloads',
            },
        ),
        migrations.CreateModel(
            name='CurrentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(verbose_name='Message ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_cloud.profile')),
            ],
            options={
                'verbose_name': 'CurrentAction',
                'verbose_name_plural': 'CurrentActions',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_cloud.role', verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='MediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_cloud.media', verbose_name='Media')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_cloud.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Media Profile',
                'verbose_name_plural': 'Media Profiles',
                'unique_together': {('media', 'profile')},
            },
        ),
    ]
